[package]
name = "lamb"
version = "0.1.0"
authors = ["nacho <sabauflorin28@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "5.1.1"
clap = {version = "2.33", features = ["yaml"]}
